Repository Seoul-InterViewer/InterViewer, pull requests merged in 2025-05, with the labels that each got.

#6 INTER-237-RadioButtonComponent
  src/app/components/radioButton/RadioButton.tsx
  src/app/components/radioButton/index.ts
  src/app/components/radioButton/page.tsx
  src/app/components/radioButton/radioButton.type.ts
  src/app/components/radioButton/radioButton.variants.ts
Labels: 🔮 Feature, 💄 Style

#4 INTER-230-InputComponent
  src/app/components/input/Input.tsx
  src/app/components/input/checkboxInput/CheckboxInput.tsx
  src/app/components/input/checkboxInput/checkboxInput.type.ts
  src/app/components/input/checkboxInput/checkboxInput.variants.ts
  src/app/components/input/checkboxInput/index.ts
  src/app/components/input/input.type.ts
  src/app/components/input/input.variants.ts
  src/app/components/input/page.tsx
  src/hooks/input/useCheckbox.ts
  src/hooks/input/useFocus.ts
  src/hooks/input/useInput.ts
  src/styles/mixins.css
  src/styles/theme.css
  src/styles/variables.css
Labels: 🔧 Chore, 🔮 Feature, 💄 Style

#7 INTER-232-IconComponent
  public/assets/icons/apple.svg
  public/assets/icons/bookmark.svg
  public/assets/icons/card-quiz.svg
  public/assets/icons/close.svg
  public/assets/icons/codepen.svg
  public/assets/icons/correct.svg
  public/assets/icons/create-new.svg
  public/assets/icons/cs.svg
  public/assets/icons/edit.svg
  public/assets/icons/github.svg
  public/assets/icons/google.svg
  public/assets/icons/heart-black.svg
  public/assets/icons/heart.svg
  public/assets/icons/hero-codepen.svg
  public/assets/icons/hero-note.svg
  public/assets/icons/hero-question.svg
  public/assets/icons/hero-quiz.svg
  public/assets/icons/horisontal-elipsis.svg
  public/assets/icons/incorrect.svg
  public/assets/icons/javascript.svg
  public/assets/icons/library.svg
  public/assets/icons/menu.svg
  public/assets/icons/nextjs.svg
  public/assets/icons/plus.svg
  public/assets/icons/question-black.svg
  public/assets/icons/react.svg
  public/assets/icons/reply.svg
  public/assets/icons/report.svg
  public/assets/icons/search.svg
  public/assets/icons/setting.svg
  public/assets/icons/share.svg
  public/assets/icons/trash.svg
  public/assets/icons/typescript.svg
  public/assets/icons/upload.svg
  public/assets/icons/user.svg
  public/assets/icons/vertical-elipsis.svg
  public/assets/icons/web.svg
  src/app/components/icon/Icon.tsx
  src/app/components/icon/icon.tsx
  src/app/components/icon/icon.type.ts
  src/app/components/icon/index.ts
  src/app/components/icon/page.tsx
  src/styles/theme.css
  src/types/svg.d.ts
Labels: 🔮 Feature, ♻️ Refactor, 💄 Style

#9 INTER-232-IconComponent - 긴급 size속성 추가 PR
  src/app/components/icon/Icon.tsx
  src/app/components/icon/icon.type.ts
  src/app/components/icon/page.tsx
Labels: ♻️ Refactor, 💡 Enhancement

#13 INTER-230-InputComponent-테스트 페이지 훅함수 사용법 도입
  src/app/components/input/checkboxInput/CheckboxInput.tsx
  src/app/components/input/page.tsx
Labels: ♻️ Refactor

#12 INTER-223-ButtonComponent
  src/app/components/button/Button.tsx
  src/app/components/button/button.type.ts
  src/app/components/button/button.variants.ts
  src/app/components/button/index.ts
  src/app/components/button/page.tsx
  src/styles/variables.css
Labels: 🔮 Feature, ♻️ Refactor, 💄 Style

#10 INTER-226-ToastComponent-토스트 컴포넌트 구현
  src/app/components/toast/Toast.tsx
  src/app/components/toast/index.ts
  src/app/components/toast/page.tsx
  src/app/components/toast/toast.type.ts
  src/app/components/toast/toast.variants.ts
  src/app/components/toast/toastContainer/ToastContainer.tsx
  src/app/layout.tsx
  src/stores/toastStore.ts
  src/types/stores/toastStore.type.ts
Labels: 🔮 Feature, 💡 Enhancement

#14 ISSUE-11-FixTailwindClasses-dev의 테일윈드 커스텀 클래스 접두어 일괄 수정
  src/app/components/input/input.variants.ts
  src/app/components/radioButton/RadioButton.tsx
  src/app/test-tailwind/page.tsx
Labels: 🐞 Bug, ♻️ Refactor

#15 INTER-226-ToastComponent-Toast 제거 버튼 Button컴포넌트로 변경
  src/app/components/toast/Toast.tsx
Labels: ♻️ Refactor, 💡 Enhancement

#16 INTER-227-ListComponent-공용 리스트 컴포넌트 구현
  src/app/components/list/List.tsx
  src/app/components/list/list.type.ts
  src/app/components/list/list.variants.ts
  src/app/components/list/page.tsx
Labels: 🔮 Feature, 💄 Style

#18 INTER-238-EmptyUIComponent-공용 컴포넌트 EmptyUI 구현
  public/images/emptyUI/bookmark.png
  public/images/emptyUI/game.png
  public/images/emptyUI/wrong-notes.png
  src/app/components/emptyUI/EmptyUI.tsx
  src/app/components/emptyUI/emptyUI.type.ts
  src/app/components/emptyUI/emptyUI.variants.ts
  src/app/components/emptyUI/index.ts
  src/app/components/emptyUI/page.tsx
  src/hooks/useViewport.ts
Labels: 🔮 Feature, 💄 Style

#27 refactor: variants 수정 #26
  src/app/components/button/button.variants.ts
  src/app/components/button/page.tsx
Labels: ♻️ Refactor, 💄 Style

#17 INTER-231-TextareaComponent-공용 텍스트에리어 컴포넌트 구현
  src/app/components/textarea/Textarea.tsx
  src/app/components/textarea/index.ts
  src/app/components/textarea/page.tsx
  src/app/components/textarea/textarea.type.ts
  src/app/components/textarea/textarea.variants.ts
Labels: 🔮 Feature, 💄 Style

#32 INTER-237-RadioButtonComponent - 폰트 사이즈 변경#11
  src/app/components/radioButton/RadioButton.tsx
  src/app/components/radioButton/radioButton.variants.ts
Labels: 💄 Style

#33 INTER-239-PaginationComponent - 공용 컴포넌트 페이지네이션 구현
  src/app/components/pagination/Pagination.tsx
  src/app/components/pagination/index.ts
  src/app/components/pagination/page.tsx
  src/app/components/pagination/pagination.type.ts
  src/app/components/pagination/pagination.variants.ts
  src/hooks/pagination/usePagination.ts
Labels: 🔮 Feature, 💄 Style

#29 INTER-225-BreadCrumbComponent-공용컴포넌트 BreadCrumb 구현
  src/app/(auth)/settings/[userId]/page.tsx
  src/app/components/bread-crumb/BreadCrumb.tsx
  src/app/components/bread-crumb/breadCrumb.type.ts
  src/app/components/bread-crumb/breadCrumb.variants.ts
  src/app/components/bread-crumb/index.ts
  src/app/components/bread-crumb/page.tsx
  src/app/globals.css
Labels: 🔮 Feature, 💄 Style

#34 INTER-236-SliderComponent-공용컴포넌트 Slider 구현
  src/app/components/slider/Slider.tsx
  src/app/components/slider/index.ts
  src/app/components/slider/page.tsx
  src/app/components/slider/slider.config.ts
  src/app/components/slider/slider.type.ts
  src/app/globals.css
  src/styles/slider.css
Labels: 🔮 Feature, 💄 Style

#35 INTER-229-TitleComponent-공용 컴포넌트 title 구현
  src/app/components/title/Title.tsx
  src/app/components/title/index.ts
  src/app/components/title/page.tsx
  src/app/components/title/title.type.ts
  src/app/components/title/title.variants.ts
Labels: 🔮 Feature, 💄 Style

#28 INTER-235-MobileMenuComponent-모바일메뉴 공용 컴포넌트 구현
  src/app/components/input/input.variants.ts
  src/app/components/mobilemenu/MobileMenu.tsx
  src/app/components/mobilemenu/MyContentMenu.tsx
  src/app/components/mobilemenu/OtherContentMenu.tsx
  src/app/components/mobilemenu/index.ts
  src/app/components/mobilemenu/mobileMenu.type.ts
  src/app/components/mobilemenu/mobileMenu.variants.ts
  src/app/components/mobilemenu/page.tsx
Labels: 🔮 Feature, 💄 Style

#31 INTER-228-TagComponent-공용 컴포넌트 태그 구현
  src/app/components/icon/Icon.tsx
  src/app/components/icon/icon.type.ts
  src/app/components/tag/Tag.tsx
  src/app/components/tag/index.ts
  src/app/components/tag/page.tsx
  src/app/components/tag/tag.type.ts
  src/app/components/tag/tag.variants.ts
Labels: 🔮 Feature, 💄 Style

#39 ISSUE-38-CreateUseRouteModal-커스텀 훅 useRouteModal 추가 #38
  src/hooks/modal/useRouteModal.ts
Labels: 🔮 Feature, 💡 Enhancement
