Repository Seoul-InterViewer/InterViewer, pull requests merged in 2025-06, with the labels that each got.

#41 INTER-257-LayoutPages-공용 레이아웃 페이지 전체 구현
  src/app/(anon)/(inner)/layout.tsx
  src/app/(anon)/(inner)/questions/[questionId]/page.tsx
  src/app/(anon)/(inner)/questions/categories/[category]/page.tsx
  src/app/(anon)/page.tsx
  src/app/(auth)/(no-header)/games/[gameId]/edit/select-blanks/page.tsx
  src/app/(auth)/(no-header)/games/[gameId]/play/page.tsx
  src/app/(auth)/(no-header)/games/create/select-blanks/page.tsx
  src/app/(auth)/(no-header)/layout.tsx
  src/app/(auth)/(with-header)/bookmarks/[bookmarkGroup]/page.tsx
  src/app/(auth)/(with-header)/bookmarks/page.tsx
  src/app/(auth)/(with-header)/games/[gameId]/edit/page.tsx
  src/app/(auth)/(with-header)/games/[gameId]/result/page.tsx
  src/app/(auth)/(with-header)/games/create/page.tsx
  src/app/(auth)/(with-header)/games/page.tsx
  src/app/(auth)/(with-header)/layout.tsx
  src/app/(auth)/(with-header)/my/@slot/game-history/page.tsx
  src/app/(auth)/(with-header)/my/@slot/my-questions/page.tsx
  src/app/(auth)/(with-header)/my/@slot/wrong-answers/page.tsx
  src/app/(auth)/(with-header)/my/layout.tsx
  src/app/(auth)/(with-header)/my/page.tsx
  src/app/(auth)/(with-header)/questions/[questionId]/edit/page.tsx
  src/app/(auth)/(with-header)/questions/create/page.tsx
  src/app/(auth)/(with-header)/settings/page.tsx
  src/app/(auth)/(with-header)/wrong-answers/[wrongAnswerId]/page.tsx
  src/app/(auth)/games/[userId]/(with-header)/layout.tsx
  src/app/(auth)/games/[userId]/(with-header)/result/[gameId]/page.tsx
  src/app/(auth)/games/[userId]/(without-header)/create/select-blanks/page.tsx
  src/app/(auth)/games/[userId]/(without-header)/edit/[gameId]/select-blanks/page.tsx
  src/app/(auth)/games/[userId]/(without-header)/play/[gameId]/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/my/[userId]/layout.tsx
  src/app/404/page.tsx
  src/app/@modal/auth/join/page.tsx
  src/app/@modal/auth/login/page.tsx
  src/app/@modal/default.tsx
  src/app/@modal/search/page.tsx
  src/app/components/emptyUI/EmptyUI.tsx
  src/app/components/header/Header.tsx
  src/app/error/403/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/hooks/modal/useRouteModal.ts
  src/lib/utils/withViewTransition.ts
Labels: 🔧 Chore, ♻️ Refactor, 💄 Style

#46 ISSUE-45-ImplementOverflowStyle-루트 레이아웃에 overflow-x hidden 추가
  src/app/layout.tsx
Labels: ♻️ Refactor, 💄 Style

#49 ISSUE-48-AddPseudoTailwindClasses-전후문자선택자에 대한 커스텀 클래스 추가 정의
  src/styles/theme.css
  src/styles/variables.css
Labels: 🔧 Chore, 💄 Style

#53 ISSUE-52-SetAutoClassnames-type에 따른 공용컴포넌트 variant className자동 할당 설정
  src/app/components/list/List.tsx
  src/app/components/list/list.type.ts
Labels: 🔮 Feature, 💄 Style, 💡 Enhancement

#55 ISSUE-54-ChangeUtilsFolderStructure-유틸 폴더 구조 변경
  src/constants/.gitkeep
  src/hooks/modal/useRouteModal.ts
  src/utils/withViewTransition.ts
Labels: 🔧 Chore, ♻️ Refactor

#57 ISSUE-56-AddIconStrokeProps-아이콘 stroke props 누락 이슈 수정 #56
  src/app/components/icon/Icon.tsx
Labels: ♻️ Refactor, 💄 Style, 💡 Enhancement

#59 ISSUE-58-AddTagStyle-padding값 변경 및 글자수 제한
  src/app/components/tag/page.tsx
  src/app/components/tag/tag.variants.ts
Labels: ♻️ Refactor, 💄 Style, 💡 Enhancement

#68 ISSUE-67-FixInputPadding-Input 공용 컴포넌트 패딩 스타일 조정
  src/app/components/input/input.variants.ts
Labels: ♻️ Refactor, 💄 Style

#69 ISSUE-63-FixCardVariants-mainCard Variants 너비 및 높이값 조절
  src/app/components/card/card.variants.ts
Labels: ♻️ Refactor, 💄 Style

#78 ISSUE-67-FixInputPadding-반응형 패딩 수정
  src/app/components/input/input.variants.ts
Labels: ♻️ Refactor, 💄 Style

#82 ISSUE-79-ExtendInputProps-ref 타입 변경
  src/app/components/input/input.type.ts
Labels: ♻️ Refactor

#81 ISSUE-73-AddHeaderLink-헤더 로그인버튼 링크로 교체, 아이콘변경
  src/app/components/header/Header.tsx
Labels: ♻️ Refactor, 💄 Style

#84 ISSUE-79-ExtendInputProps-ref 제네릭 타입 변경
  src/app/components/input/input.type.ts
Labels: ♻️ Refactor

#71 INTER-241-MainPage-메인페이지 UI 구현
  src/app/(anon)/components/banner/Banner.tsx
  src/app/(anon)/components/banner/banner.variants.ts
  src/app/(anon)/components/banner/bannerCard/BannerCard.tsx
  src/app/(anon)/components/banner/bannerCard/bannerCard.type.ts
  src/app/(anon)/components/banner/bannerCard/bannerCard.variants.ts
  src/app/(anon)/components/banner/bannerCard/bannerCardsData.constants.ts
  src/app/(anon)/components/banner/bannerCard/index.ts
  src/app/(anon)/components/banner/index.ts
  src/app/(anon)/components/mainCard/MainCard.tsx
  src/app/(anon)/components/mainCard/index.ts
  src/app/(anon)/components/mainCard/mainCard.type.ts
  src/app/(anon)/mocks/mainCardData.mock.ts
  src/app/(anon)/page.tsx
  src/constants/categoryIcons.ts
  src/types/utils/categoryIconMapper.type.ts
  src/utils/capitalize.ts
  src/utils/categoryIconMapper.ts
Labels: 🔮 Feature, 💄 Style

#47 INTER-258-NotFoundPage-404페이지 구현
  src/app/components/NotFound/NotFound.tsx
  src/app/not-found.tsx
Labels: 🔮 Feature, 💄 Style

#95 ISSUE-94-AddClassNameCardComponent-카드컴포넌트 className추가
  src/app/components/card/Card.tsx
  src/app/components/card/card.type.ts
  src/app/components/card/card.variants.ts
Labels: ♻️ Refactor

#93 ISSUE-92-AddMotionWrapper-공용컴포넌트 프레이머 모션 Wrapper 컴포넌트 구현
  src/app/components/motionWrapper/MotionWrapper.tsx
  src/app/components/motionWrapper/index.ts
  src/app/components/motionWrapper/motionWrapper.type.ts
  src/app/components/motionWrapper/page.tsx
Labels: 🔮 Feature, 💄 Style

#99 ISSUE-96-CorectAnswerRate-컴포넌트 폴더 이동
  src/app/(auth)/(with-header)/components/correctAnswerRate/CorrectAnswerRate.tsx
  src/app/(auth)/(with-header)/components/correctAnswerRate/correctAnswerRate.type.ts
  src/app/(auth)/(with-header)/components/correctAnswerRate/correctAnswerRate.variants.ts
  src/app/(auth)/(with-header)/components/correctAnswerRate/index.ts
  src/app/(auth)/(with-header)/components/correctAnswerRate/page.tsx
  src/app/(auth)/(with-header)/components/types/getAverageScore.type.ts
  src/app/(auth)/(with-header)/components/utils/getAverageScore.ts
Labels: ♻️ Refactor

#102 ISSUE-101-AddAnimationCorrectAnswerRate-CorrectAnswerRate컴포넌트에 애니메이션 추가
  src/app/(auth)/(with-header)/components/correctAnswerRate/CorrectAnswerRate.tsx
Labels: 🔮 Feature, 💄 Style, 💡 Enhancement
